/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.ems;

import com.csvreader.CsvReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        
        initComponents();
        
        registerComboBox.removeAllItems();
        registerComboBox.addItem("Student");
        registerComboBox.addItem("Company");
        
        companyNameTextField.setVisible(false);
        companyAddressTextField.setVisible(false);
        companyProfileLinkTextField.setVisible(false);
        companyNameLabel.setVisible(false);
        companyAddressLabel.setVisible(false);
        companyProfileLabel.setVisible(false);
        
        userComboBox.removeAllItems();
        userComboBox.addItem("Student");
        userComboBox.addItem("Company");
        
        // dobDateChooser.setDate(new Date());
        
        qualificationComboBox.removeAllItems();
        
        String qualifications[] = new String[5];
        qualifications[0] = "B.Tech.";
        qualifications[1] = "M.Tech.";
        qualifications[2] = "Senoor Secondary";
        qualifications[3] = "Secondary";
        qualifications[4] = "Other";
        
        for (String x : qualifications) {
            qualificationComboBox.addItem(x);
        }
        
        companyProfileLinkTextField.setText("Url of your company profile");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginEmailTextField = new javax.swing.JTextField();
        loginPasswordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        userComboBox = new javax.swing.JComboBox();
        forgotPasswordLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        studentLastNameTextField = new javax.swing.JTextField();
        registerContactTextField = new javax.swing.JTextField();
        studentFirstNameTextField = new javax.swing.JTextField();
        marksSpinner = new javax.swing.JSpinner();
        qualificationComboBox = new javax.swing.JComboBox();
        registerEmailTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        marksLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        qualificationLabel = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        companyNameTextField = new javax.swing.JTextField();
        companyAddressLabel = new javax.swing.JLabel();
        companyProfileLinkTextField = new javax.swing.JTextField();
        companyProfileLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        companyAddressTextField = new javax.swing.JTextArea();
        otherDegreeTextField = new javax.swing.JTextField();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        registerComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Password    :");

        loginEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEmailTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username :");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        userComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        forgotPasswordLabel.setText("Forgot password ?");

        jLabel10.setText("Login as :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel10)
                        .addGap(66, 66, 66)
                        .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 262, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(forgotPasswordLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(loginPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(33, 33, 33)
                .addComponent(forgotPasswordLabel)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jLabel8.setText("Contact number");

        studentLastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLastNameTextFieldActionPerformed(evt);
            }
        });

        registerContactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerContactTextFieldActionPerformed(evt);
            }
        });

        qualificationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        firstNameLabel.setText("First name");

        marksLabel.setText("Marks");

        jLabel9.setText("Email id");

        dobLabel.setText("Date of birth");

        lastNameLabel.setText("Last name");

        qualificationLabel.setText("Last Qualification degree");

        companyNameLabel.setText("Company name");

        companyAddressLabel.setText("Company address");

        companyProfileLinkTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyProfileLinkTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyProfileLinkTextFieldFocusLost(evt);
            }
        });

        companyProfileLabel.setText("Company Profile");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        companyAddressTextField.setColumns(20);
        companyAddressTextField.setRows(5);
        jScrollPane1.setViewportView(companyAddressTextField);

        otherDegreeTextField.setText("In case of other specify here");
        otherDegreeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otherDegreeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                otherDegreeTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(marksLabel)
                        .addGap(161, 161, 161)
                        .addComponent(marksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(qualificationLabel)
                            .addComponent(dobLabel)
                            .addComponent(companyAddressLabel)
                            .addComponent(companyProfileLabel)
                            .addComponent(companyNameLabel)
                            .addComponent(jLabel9)
                            .addComponent(lastNameLabel)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentFirstNameTextField)
                            .addComponent(otherDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qualificationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentLastNameTextField)
                            .addComponent(registerContactTextField)
                            .addComponent(registerEmailTextField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addComponent(companyNameTextField)
                            .addComponent(companyProfileLinkTextField)
                            .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addGap(66, 66, 66)
                        .addComponent(dobLabel)
                        .addGap(18, 18, 18)
                        .addComponent(qualificationLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(studentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel))
                        .addGap(4, 4, 4)
                        .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qualificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marksLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(marksSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerContactTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerEmailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(companyNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyAddressLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(companyProfileLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(companyProfileLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addComponent(registerButton)
                .addGap(22, 22, 22))
        );

        registerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        registerComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                registerComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        registerComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerComboBoxMouseClicked(evt);
            }
        });
        registerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setText("Register as:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(registerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Register", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailTextFieldActionPerformed

    private void companyProfileLinkTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyProfileLinkTextFieldFocusGained
        if (companyProfileLinkTextField.getText().equals("Url of your company profile")) {
            companyProfileLinkTextField.setText("");
        }
    }//GEN-LAST:event_companyProfileLinkTextFieldFocusGained

    private void companyProfileLinkTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyProfileLinkTextFieldFocusLost
        if (companyProfileLinkTextField.getText().equals("")) {
            companyProfileLinkTextField.setText("Url of your company profile");
        }
    }//GEN-LAST:event_companyProfileLinkTextFieldFocusLost

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String loginEmail, loginPassword;
        loginEmail = loginEmailTextField.getText().trim();
        loginPassword = loginPasswordTextField.getText().trim();
        if (loginEmail.equals("") || loginPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Both fields are necessary", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        loginEmailTextField.setText("");
        loginPasswordTextField.setText("");
        switch (userComboBox.getSelectedItem().toString()) {
            case "Student":
                loginStudent(loginEmail, loginPassword);
                break;
            case "Company":
                loginCompany(loginEmail, loginPassword);
                break;
            default :
                JOptionPane.showMessageDialog(null, "error login", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void studentLastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLastNameTextFieldActionPerformed

    private void registerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerComboBoxActionPerformed
        
    }//GEN-LAST:event_registerComboBoxActionPerformed

    private void registerComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerComboBoxMouseClicked
        
    }//GEN-LAST:event_registerComboBoxMouseClicked

    private void registerComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_registerComboBoxPopupMenuWillBecomeInvisible
        switch (registerComboBox.getSelectedItem().toString()) {
            case "Student":
                companyNameTextField.setVisible(false);
                companyAddressTextField.setVisible(false);
                companyProfileLinkTextField.setVisible(false);
                companyNameLabel.setVisible(false);
                companyAddressLabel.setVisible(false);
                companyProfileLabel.setVisible(false);
                studentFirstNameTextField.setVisible(true);
                studentLastNameTextField.setVisible(true);
                dobDateChooser.setVisible(true);
                qualificationComboBox.setVisible(true);
                otherDegreeTextField.setVisible(true);
                marksSpinner.setVisible(true);
                firstNameLabel.setVisible(true);
                lastNameLabel.setVisible(true);
                dobLabel.setVisible(true);
                qualificationLabel.setVisible(true);
                marksLabel.setVisible(true);
                break;
            case "Company" :
                companyNameTextField.setVisible(true);
                companyAddressTextField.setVisible(true);
                companyProfileLinkTextField.setVisible(true);
                companyNameLabel.setVisible(true);
                companyAddressLabel.setVisible(true);
                companyProfileLabel.setVisible(true);
                studentFirstNameTextField.setVisible(false);
                studentLastNameTextField.setVisible(false);
                dobDateChooser.setVisible(false);
                qualificationComboBox.setVisible(false);
                otherDegreeTextField.setVisible(false);
                marksSpinner.setVisible(false);
                firstNameLabel.setVisible(false);
                lastNameLabel.setVisible(false);
                dobLabel.setVisible(false);
                qualificationLabel.setVisible(false);
                marksLabel.setVisible(false);
                break;
            default:
                
        }
    }//GEN-LAST:event_registerComboBoxPopupMenuWillBecomeInvisible

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String email = registerEmailTextField.getText().toLowerCase().trim();
        long contactNumber;
        if (!isValidEmailAddress(email)) {
            JOptionPane.showMessageDialog(null, "Email address is not valid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            contactNumber = Long.parseLong(registerContactTextField.getText().trim());
            if (!isValidContactNumber(String.valueOf(contactNumber))) {
                JOptionPane.showMessageDialog(null, "Contact number is not valid ", "Error", JOptionPane.ERROR_MESSAGE);
                registerContactTextField.setText("");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Contact number is not valid", "Error", JOptionPane.ERROR_MESSAGE);
            registerContactTextField.setText("");
            return;
        }
        String user = registerComboBox.getSelectedItem().toString();
        switch(user) {
            case "Student" :
            registerStudent(email, contactNumber);
            break;
            case "Company" :
            registerCompany(email, contactNumber);
            break;
            default:

        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerContactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerContactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerContactTextFieldActionPerformed

    private void otherDegreeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherDegreeTextFieldFocusGained
        if (otherDegreeTextField.getText().equals("In case of other specify here")) {
            otherDegreeTextField.setText("");
        }
    }//GEN-LAST:event_otherDegreeTextFieldFocusGained

    private void otherDegreeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherDegreeTextFieldFocusLost
        if (otherDegreeTextField.getText().equals("")) {
            otherDegreeTextField.setText("In case of other specify here");
        }
    }//GEN-LAST:event_otherDegreeTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyAddressLabel;
    private javax.swing.JTextArea companyAddressTextField;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JLabel companyProfileLabel;
    private javax.swing.JTextField companyProfileLinkTextField;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginEmailTextField;
    private javax.swing.JPasswordField loginPasswordTextField;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JSpinner marksSpinner;
    private javax.swing.JTextField otherDegreeTextField;
    private javax.swing.JComboBox qualificationComboBox;
    private javax.swing.JLabel qualificationLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox registerComboBox;
    private javax.swing.JTextField registerContactTextField;
    private javax.swing.JTextField registerEmailTextField;
    private javax.swing.JTextField studentFirstNameTextField;
    private javax.swing.JTextField studentLastNameTextField;
    private javax.swing.JComboBox userComboBox;
    // End of variables declaration//GEN-END:variables

    private void loginStudent(String email, String pass) {
        
        Student student = null;
        boolean isLoggedIn = false;
        String isFirstTime = "0";
        
        try {
            CsvReader students = new CsvReader("students.csv");
            
            students.readHeaders();
            
            while (students.readRecord()) {
                String e = students.get("username");
                String p = students.get("password");
                
                if (email.equalsIgnoreCase(e) && pass.equals(p)) {
                    // registration success
                    isLoggedIn = true;
                    student = new Student(
                            students.get("firstName")
                            , students.get("lastName")
                            , Long.parseLong(students.get("dob"))
                            , students.get("degree")
                            , Integer.parseInt(students.get("marks"))
                            , Long.parseLong(students.get("contactNumber"))
                            , students.get("emailId")
                    );
                    student.setId(Integer.parseInt(students.get("id")));
                    isFirstTime = students.get("isFirstTime");
                    break;
                }
            
            }
            
            students.close();
            if (isLoggedIn) {
                if (isFirstTime.equals("1")) {
                    SetPasswordPage setPasswordPage = new SetPasswordPage(student, email);
                    setPasswordPage.setVisible(true);
                    dispose();
                } else {
                    StudentHome studentHome = new StudentHome(student, email);
                    studentHome.setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or/and password", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Unable to access database", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error logging in", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loginCompany(String email, String pass) {
        
        Company company = null;
        boolean isLoggedIn = false;
        String isFirstTime = "0";
        
        try {
            CsvReader companies = new CsvReader("companies.csv");
            
            companies.readHeaders();
            
            while (companies.readRecord()) {
                String e = companies.get("username");
                String p = companies.get("password");
                
                if (email.equalsIgnoreCase(e) && pass.equals(p)) {
                    // registration success
                    isLoggedIn = true;
                    company = new Company(
                            companies.get("companyName")
                            , companies.get("address")
                            , companies.get("profileLink")
                            , companies.get("emailId")
                            , Long.parseLong(companies.get("contactNumber"))
                    );
                    company.setId(Integer.parseInt(companies.get("id")));
                    isFirstTime = companies.get("isFirstTime");
                    break;
                }
            
            }
            
            companies.close();
            
            if (isLoggedIn) {
                if (isFirstTime.equals("1")) {
                    SetPasswordPage setPasswordPage = new SetPasswordPage(company, email);
                    setPasswordPage.setVisible(true);
                    dispose();
                } else {
                    //JOptionPane.showMessageDialog(null, "Sucess");
                    CompanyHome companyHome = new CompanyHome(company, email);
                    companyHome.setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or/and password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Unable to access database", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error logging in", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
    
    public boolean isValidContactNumber(String s) {
        if (s.length() == 10) return true;
        return false;
    }

    private void registerStudent(String email, long cn) {
        
        String fname = studentFirstNameTextField.getText().trim();
        String lname = studentLastNameTextField.getText().trim();
        
        Date currentDate = new Date();
        long cl = currentDate.getTime();
        
        
        Date d = dobDateChooser.getDate();
        long dob;
        try {
            dob = d.getTime();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Choose date of birth", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long diff = cl - dob;
        
        if (diff <= 0) {
            JOptionPane.showMessageDialog(null, "Are you kidding ? \n Select right date of birth.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String deg = qualificationComboBox.getSelectedItem().toString();
        String d2;
        if (deg.equals("Other")) {
            d2 = otherDegreeTextField.getText().trim();
            if (d2.equals("") || d2.equals("In case of other specify here")) {
                JOptionPane.showMessageDialog(null, "Please, specify degree", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            deg = d2;
        }
        
        int marks = Integer.parseInt(marksSpinner.getValue().toString());
        
        if (fname.equals("") || lname.equals("") || deg.equals("") || marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(null, "All fields are necessary and"
                    + " marks must be in the range [0, 100]", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Student student = new Student(fname, lname, dob, deg, marks, cn, email);
        int resultCode = student.getNumberOfStudents();
        if (resultCode == -1) {
            JOptionPane.showMessageDialog(null, "This email address is already registered", "Error", JOptionPane.ERROR_MESSAGE);
            registerEmailTextField.setText("");
            return;
        }
        
        studentFirstNameTextField.setText("");
        studentLastNameTextField.setText("");
        marksSpinner.setValue(0);
        registerEmailTextField.setText("");
        registerContactTextField.setText("");
        dobDateChooser.cleanup();
        
        student.setId(resultCode + 1);
        int result = student.RegisterStudent("1");
        switch (result) {
            case 0:
                JOptionPane.showMessageDialog(null, "Can not register at the moment, try later", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
        
    }
    private void registerCompany(String email, long cn) {
        String name = companyNameTextField.getText();
        String address = companyAddressTextField.getText();
        String profileLink = companyProfileLinkTextField.getText();
        
        if (name.equals("") || address.equals("") || profileLink.equals("") || 
                profileLink.equals("Url of your company profile")) {
            JOptionPane.showMessageDialog(this, "All fields are necessary ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Company company = new Company(name, address, profileLink, email, cn);
        int resultCode = company.getNumberOfCompanies();
        if (resultCode == -1) {
            JOptionPane.showMessageDialog(this, "This email address is already registered","Error", JOptionPane.ERROR_MESSAGE);
            registerEmailTextField.setText("");
            return;
        }
        
        companyNameTextField.setText("");
        companyAddressTextField.setText("");
        companyProfileLinkTextField.setText("");
        registerEmailTextField.setText("");
        registerContactTextField.setText("");
        
        company.setId(resultCode + 1);
        company.RegisterCompany("1");
    }
}
