/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.ems;

import com.csvreader.CsvReader;
import com.csvreader.CsvWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author himanshu
 */
public class StudentProfile extends javax.swing.JFrame {
    
    private Student student;
    private String qualifications[];

    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
        
        degreeComboBox.removeAllItems();
        
        qualifications = new String[5];
        qualifications[0] = "B.Tech.";
        qualifications[1] = "M.Tech.";
        qualifications[2] = "Senoor Secondary";
        qualifications[3] = "Secondary";
        qualifications[4] = "Other";
        
        for (String x : qualifications) {
            degreeComboBox.addItem(x);
        }
        
    }
    
    public StudentProfile(Student student, String username) {
        initComponents();
        this.student = student;
        
        degreeComboBox.removeAllItems();
        
        qualifications = new String[5];
        qualifications[0] = "B.Tech.";
        qualifications[1] = "M.Tech.";
        qualifications[2] = "Senoor Secondary";
        qualifications[3] = "Secondary";
        qualifications[4] = "Other";
        
        for (String x : qualifications) {
            degreeComboBox.addItem(x);
        }
        
        usernameLabel.setText(username);
        nameLabel.setText(this.student.getFirstName() + " " + this.student.getLastName());
        long dob = this.student.getDOB();
        
        SimpleDateFormat formatter = new SimpleDateFormat("MMM dd, YYYY");
        String formattedDate = formatter.format(new Date(dob));
        dobLabel.setText(formattedDate);
        String degree = this.student.getDegree();
        if (!isDegreeInArray(qualifications, degree)) {
            degreeComboBox.addItem(degree);
        }
        degreeComboBox.setSelectedItem(degree);
        marksSpinner.setValue(this.student.getMarks());
        contactLabel.setText(String.valueOf(this.student.getContact()));
        emailLabel.setText(this.student.getEmailId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        degreeComboBox = new javax.swing.JComboBox<>();
        otherDegreeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        marksSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name :");

        jLabel2.setText("Date of Birth :");

        jLabel3.setText("Last Qualification Degree:");

        nameLabel.setText("firstname lastname");

        dobLabel.setText("dd/MM/YYYY");

        degreeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        degreeComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                degreeComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        otherDegreeTextField.setText("In case of other, specify here");
        otherDegreeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otherDegreeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                otherDegreeTextFieldFocusLost(evt);
            }
        });

        jLabel6.setText("Username :");

        usernameLabel.setText("username");

        jLabel8.setText("Marks :");

        jLabel9.setText("Contact Number :");

        jLabel10.setText("Email address :");

        contactLabel.setText("9876543210");

        emailLabel.setText("username@gmail.com");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabel13.setText("Student Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addComponent(contactLabel)
                    .addComponent(usernameLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dobLabel)
                        .addComponent(nameLabel)
                        .addComponent(degreeComboBox, 0, 288, Short.MAX_VALUE)
                        .addComponent(otherDegreeTextField))
                    .addComponent(marksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dobLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(degreeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(otherDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(marksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(contactLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degreeComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_degreeComboBoxPopupMenuWillBecomeInvisible
        
    }//GEN-LAST:event_degreeComboBoxPopupMenuWillBecomeInvisible

    private void otherDegreeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherDegreeTextFieldFocusGained
        String otherText = otherDegreeTextField.getText().trim();
        if (otherText.equals("In case of other, specify here")) {
            otherDegreeTextField.setText("");
        }
    }//GEN-LAST:event_otherDegreeTextFieldFocusGained

    private void otherDegreeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherDegreeTextFieldFocusLost
        String otherText = otherDegreeTextField.getText().trim();
        if (otherText.equals("")) {
            otherDegreeTextField.setText("In case of other, specify here");
        }
    }//GEN-LAST:event_otherDegreeTextFieldFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // save the profile of the student
        int marks = (int) marksSpinner.getValue();
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(null, "Marks must be in the range [0, 100]", "Error", JOptionPane.ERROR_MESSAGE);
            marksSpinner.setValue(0);
            return;
        } 
        String d1 = degreeComboBox.getSelectedItem().toString();
        String d2;
        if (d1.equals("Other")) {
            d2 = otherDegreeTextField.getText().trim();
            if (d2.equals("") || d2.equals("In case of other, specify here")) {
                JOptionPane.showMessageDialog(null, "Please, specify degree", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            d1 = d2;
        }
        
        this.student.setMarks(marks);
        this.student.setDegree(d1);
        
        String filelocation = "students.csv";
        
        CsvReader reader2 = null;
        try {
            reader2 = new CsvReader(new FileReader(filelocation));
            ArrayList<String[]> allElements = new ArrayList<>();
            reader2.readHeaders();
            while(reader2.readRecord()) {
                allElements.add(reader2.getValues());
                
            }
            reader2.close();
            
            (allElements.get(this.student.getId() - 1))[5] = d1;
            (allElements.get(this.student.getId() - 1))[6] = String.valueOf(marks);
            
            CsvWriter csvOutput = new CsvWriter(new FileWriter(filelocation, false), ',');
            
            csvOutput.write("id");
            csvOutput.write("username");
            csvOutput.write("firstName");
            csvOutput.write("lastName");
            csvOutput.write("dob");
            csvOutput.write("degree");
            csvOutput.write("marks");
            csvOutput.write("contactNumber");
            csvOutput.write("emailId");
            csvOutput.write("password");
            csvOutput.write("isFirstTime");
            csvOutput.endRecord();
            
            for (String[] x: allElements) {
                csvOutput.writeRecord(x);
            }
            csvOutput.close();
            
            JOptionPane.showMessageDialog(null, "Done! Your profile has been updated");
            dispose();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            reader2.close();
        }        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JComboBox<String> degreeComboBox;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner marksSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField otherDegreeTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    private boolean isDegreeInArray(String[] qualifications, String degree) {
        for (String x : qualifications) {
            if (x.equals(degree)) return true;
        }
        return false;
    }
}
